name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.12.0
        include:
          - ocaml-version: 4.03.0
            os: ubuntu-latest
            skip_test: true
          - ocaml-version: 4.08.1
            os: ubuntu-latest
            skip_test: true
          - ocaml-version: 4.11.1
            os: ubuntu-latest
            skip_test: true
          - ocaml-version: 4.13.0
            os: ubuntu-latest
            skip_test: true
          - ocaml-version: 4.13.0
            arch: armv6
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    env:
      SKIP_TEST: ${{ matrix.skip_test }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up OCaml ${{ matrix.ocaml-version }} on ${{ matrix.os }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build @install @demo
      - name: run test suite
        run: opam exec -- dune exec demo/demo.exe
        if: env.SKIP_TEST != 'true'
